-- 1. Create the table
create table admin_whitelist (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable Row Level Security (RLS)
alter table admin_whitelist enable row level security;

-- 3. Create Policy: Users can only see if THEY are in the list
-- This prevents anyone from reading the full list of admins.
create policy "Users can read own admin status"
on admin_whitelist for select
to authenticated
using (
  email = auth.jwt() ->> 'email'
);

-- 4. Add your email (CHANGE THIS to your actual email!)
insert into admin_whitelist (email)
values ('oshadakalindu@gmail.com');
